version: '3.2'
services:
  postgres:
    image: postgres:12
    container_name: microservices-postgres
    restart: always
    ports:
      - '6543:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: devpassword

  rabbitmq:
    image: rabbitmq:3.8.5-management-alpine
    container_name: microservices-rabbitmq
    restart: always
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    image: mongo:4.2.8
    container_name: microservices-mongodb
    restart: always
    ports:
      - 27017:27017

  redis:
    image: redis:6.0.6-alpine
    container_name: microservices-redis
    restart: always
    ports:
      - 6380:6379

volumes:
  db_data:
